import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import Main from "@/components/main";
import { ThemeProvider } from "@/components/ThemeContext";
import Navbar from "@/components/Navbar";
import "./globals.css";

const Noto = Noto_Sans({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Noto.className}`}>
        <ThemeProvider>
          <Navbar/>
        <Main>
          {children}
        </Main>
        </ThemeProvider>  
      </body>
    </html>
  );
}
